### ISSUE TITLE
Install without firefox-gnome-theme

### ISSUE THREAD

**Issue by dchinmay2** [rafaelmardojai/firefox-gnome-scrollbars#12]
Title. Is it possible to get overlay scrollbars without firefox-gnome-theme?

**Comment by rafaelmardojai** [comment]
Yes
![Captura de pantalla de 2020-12-09 09-06-30](https://user-images.githubusercontent.com/6210397/101639892-db149380-39fd-11eb-8797-cbec1a7ba8fd.png)

**Comment by dchinmay2** [comment]
i guess I need to reinstall firefox then? i uninstalled firefox-gnome-theme using the given instructions and the scrollbars reverted too.
I then tried installing firefox-gnome-scrollbars again

**Comment by rafaelmardojai** [comment]
Yes, you probably removed the hole `chrome` folder. In this case you should only remove the `firefox-gnome-theme` folder.

I need to clarify that in the README.

**Comment by dchinmay2** [comment]
This time I only removed the firefox-gnome-theme folder, yet they reverted to standard

**Comment by dchinmay2** [comment]
in the meantime,
```css
/* ==UserStyle==
@name         overlay-scrollbars
@version      2.0.1
@description  Global overlay scrollbars for Firefox
@namespace    silverwind
@author       silverwind
@homepageURL  https://github.com/silverwind/overlay-scrollbars
@supportURL   https://github.com/silverwind/overlay-scrollbars/issues
@license      BSD-2-clause

@advanced color custom-scrollbar-color "Scrollbar color" rgba(128, 128, 128, .5)"
@advanced color custom-track-color "Track color" "transparent"
==/UserStyle== */

* {
  scrollbar-color: /*[[custom-scrollbar-color]]*/ /*[[custom-track-color]]*/ !important;
  scrollbar-width: thin !important;
}
```
with stylus works
